using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace LearnEnglishVocab.Model
{
    public class VocabularyData
    {
        private int id { get; set; }
        public string courseName { get; set; }
        public string level { get; set; }
        public string language { get; set; }
        public string englishWord { get; set; }
        public string polishWord { get; set; }

        public string imagePath { get; set; }

        // for construction of new VocabularyData objects without id, which will be generated by the database
        public VocabularyData(string courseName, string level, string language,string englishWord, string polishWord)
        {
            this.courseName = courseName;
            this.level = level;
            this.language = language;
            this.englishWord = englishWord;
            this.polishWord = polishWord;
        }

        //api calls
        public VocabularyData(int id, string courseName, string level, string langauge, string englishWord, string polishWord, string imagePath)
        {
            this.id = id;
            this.courseName = courseName;
            this.level = level;
            this.language = langauge;
            this.englishWord = englishWord;
            this.polishWord = polishWord;
            this.imagePath = imagePath;
        }

    }
}
